/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ziaskincare;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import ziaskincare.config.UserLoginUtil;
import ziaskincare.komponen.Center;

/**
 *
 * @author Ai
 */
public class MenuLayout extends javax.swing.JFrame {

    private String userName;
    /**
     * Creates new form MasterLayout
     */
    
    public MenuLayout(String userName){
        this.userName = userName;
    }
    
    public MenuLayout() {
        initComponents();
        Center Center = new Center(this);
        //UserLoginUtil.setUserName("hohohohohohohohoho");
        txtUsername.setText(userName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public JLabel getjLabel1() {
        return null;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        panel1 = new ziaskincare.komponen.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        master = new javax.swing.JMenu();
        datasatuan = new javax.swing.JMenuItem();
        datakategori = new javax.swing.JMenuItem();
        databarang = new javax.swing.JMenuItem();
        datapetugas = new javax.swing.JMenuItem();
        datapelanggan = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        sistem = new javax.swing.JMenu();
        log_out = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ziaskincare/picture/IMG-20151217-WA0004.jpg"))); // NOI18N
        panel1.add(jLabel1);
        jLabel1.setBounds(240, 170, 227, 155);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 0));
        jLabel2.setText("SELAMAT DATANG");
        panel1.add(jLabel2);
        jLabel2.setBounds(220, 30, 260, 35);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 0));
        jLabel3.setText(" DI APLIKASI ZIA SKIN CARE TASIKMALAYA");
        panel1.add(jLabel3);
        jLabel3.setBounds(70, 80, 590, 35);
        panel1.add(txtUsername);
        txtUsername.setBounds(540, 170, 70, 20);

        master.setText("MASTER");

        datasatuan.setText("Data Satuan");
        datasatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datasatuanActionPerformed(evt);
            }
        });
        master.add(datasatuan);

        datakategori.setText("Data Kategori");
        datakategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datakategoriActionPerformed(evt);
            }
        });
        master.add(datakategori);

        databarang.setText("Data Barang");
        databarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databarangActionPerformed(evt);
            }
        });
        master.add(databarang);

        datapetugas.setText("Data Petugas");
        datapetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datapetugasActionPerformed(evt);
            }
        });
        master.add(datapetugas);

        datapelanggan.setText("Data Pelanggan");
        datapelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datapelangganActionPerformed(evt);
            }
        });
        master.add(datapelanggan);

        jMenuBar2.add(master);

        jMenu4.setText("TRANSAKSI");

        jMenuItem4.setText("Transaksi");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("LAPORAN");

        jMenuItem5.setText("Laporan Data Barang");
        jMenu5.add(jMenuItem5);

        jMenuItem6.setText("Laporan Data Transaksi");
        jMenu5.add(jMenuItem6);

        jMenuBar2.add(jMenu5);

        sistem.setText("SYSTEM");

        log_out.setText("Log Out");
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });
        sistem.add(log_out);

        jMenuItem2.setText("Help");
        sistem.add(jMenuItem2);

        jMenuItem3.setText("About Developer");
        sistem.add(jMenuItem3);

        jMenuBar2.add(sistem);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datapetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datapetugasActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        DataPetugasLayout Q;
        try {
            Q = new DataPetugasLayout();
            //Q.getNamaPetugas().setText(.getText());
            Q.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuLayout.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuLayout.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_datapetugasActionPerformed

    private void databarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databarangActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        DataBarangLayout Q;
   
        try {
            Q = new DataBarangLayout();
            Q.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuLayout.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuLayout.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_databarangActionPerformed

    private void datasatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datasatuanActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        DataSatuanLayout Q;
        
        try {   
            Q = new DataSatuanLayout();
            Q.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuLayout.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuLayout.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(MenuLayout.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_datasatuanActionPerformed

    private void datakategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datakategoriActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        DataKategoriLayout Q;
        try {
            Q = new DataKategoriLayout();
            Q.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuLayout.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuLayout.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_datakategoriActionPerformed

    private void datapelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datapelangganActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        DataPelangganLayout Q;
        try {
            Q = new DataPelangganLayout();
             Q.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuLayout.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuLayout.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_datapelangganActionPerformed

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_log_outActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
                setVisible(false);
        TransaksiLayout Q;
        try {
            Q = new TransaksiLayout();
            Q.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuLayout.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuLayout.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuLayout().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem databarang;
    private javax.swing.JMenuItem datakategori;
    private javax.swing.JMenuItem datapelanggan;
    private javax.swing.JMenuItem datapetugas;
    private javax.swing.JMenuItem datasatuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem log_out;
    private javax.swing.JMenu master;
    private ziaskincare.komponen.Panel panel1;
    private javax.swing.JMenu sistem;
    private javax.swing.JLabel txtUsername;
    // End of variables declaration//GEN-END:variables
}
